### ISSUE TITLE
VerifyError: java.lang.VerifyError: (class: mondrian/rolap/RolapCube, method:   signature: (Lmondrian/rolap/RolapSchema;Lmondrian/olap/MondrianDef$Schema;Lmondrian/olap/MondrianDef$Cube;Z)V) Register 7 contains wrong type

### ISSUE THREAD

**Issue by rahrai** [pentaho/mondrian#1067]
I am populating OLAP database using Mondrain API but get the below error only for the first time when we run the job...When we run the second time...it works...What could be the issue?

I am using JBOSS EAP 6.4 and olap4j.jar version:1.0.1.500

1. TechnicalException: XXX-001 - A technical error occurred. Please refer to next layer and stacktrace for further details.
2. CallException: Could not invoke test.xxxxx.dao.report.funds.mi.PopulateOlap.execute with arguments 
3. InvocationTargetException: java.lang.reflect.InvocationTargetException
4. VerifyError: java.lang.VerifyError: (class: mondrian/rolap/RolapCube, method:   signature: (Lmondrian/rolap/RolapSchema;Lmondrian/olap/MondrianDef$Schema;Lmondrian/olap/MondrianDef$Cube;Z)V) Register 7 contains wrong type
	at mondrian.rolap.RolapSchema.load(RolapSchema.java:559)
	at mondrian.rolap.RolapSchema.load(RolapSchema.java:434)
	at mondrian.rolap.RolapSchema. (RolapSchema.java:240)
	at mondrian.rolap.RolapSchema. (RolapSchema.java:60)
	at mondrian.rolap.RolapSchema$Pool.get(RolapSchema.java:1121)
	at mondrian.rolap.RolapSchema$Pool.get(RolapSchema.java:913)
	at mondrian.rolap.RolapConnection. (RolapConnection.java:151)
	at mondrian.rolap.RolapConnection. (RolapConnection.java:87)
	at mondrian.olap.DriverManager.getConnection(DriverManager.java:112)
	at mondrian.olap.DriverManager.getConnection(DriverManager.java:71)
	at mondrian.olap.DriverManager.getConnection(DriverManager.java:53)
	at test.xxxxx.dao.report.funds.mi.PopulateOlapDAO.flushOlapCache(PopulateOlapDAO.java:194)
	at test.xxxxx.dao.report.funds.mi.PopulateOlapDAO.execute(PopulateOlapDAO.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.sqlb.call.dao.DAOFactoryImpl$DAOInvocationHandler.invoke(DAOFactoryImpl.java:148)
	at com.sun.proxy.$Proxy1875.execute(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.sqlb.call.dao.DAOPreparedCall.invoke(DAOPreparedCall.java:303)
	at org.sqlb.call.dao.DAOPreparedCall.execute(DAOPreparedCall.java:167)
	at org.sqlb.call.delegate.server.CallDelegateBase.runCalls(CallDelegateBase.java:437)
	at org.sqlb.call.delegate.server.CallDelegateBase.doRun(CallDelegateBase.java:359)
	at org.sqlb.call.delegate.server.CallDelegateBase.run(CallDelegateBase.java:310)
	at org.sqlb.call.delegate.server.CallDelegateBase.runVoid(CallDelegateBase.java:250)
	at org.sqlb.call.delegate.server.CallDelegateBase.call(CallDelegateBase.java:63)
	at sun.reflect.GeneratedMethodAccessor751.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53)
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53)
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.tx.EjbBMTInterceptor.handleInvocation(EjbBMTInterceptor.java:104)
	at org.jboss.as.ejb3.tx.BMTInterceptor.processInvocation(BMTInterceptor.java:60)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:21)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
	at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:53)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterceptor.java:43)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:59)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:55)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ee.component.TCCLInterceptor.processInvocation(TCCLInterceptor.java:45)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
	at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:185)
	at org.jboss.as.ee.component.ViewDescription$1.processInvocation(ViewDescription.java:185)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
	at org.jboss.as.ee.component.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:73)
	at org.sqlb.call.delegate.server.CallDelegate$$$view9.call(Unknown Source)
	at org.sqlb.call.delegate.client.CallDelegateAUTOWrapper.call(CallDelegateAUTOWrapper.java:54)
	at org.sqlb.call.delegate.client.PreparedCallStub.delegateCall(PreparedCallStub.java:125)
	at test.commons.engine.db.DBQueueItem.execPreparedCall(DBQueueItem.java:207)
	at test.commons.engine.db.DBQueueItem.execDAO(DBQueueItem.java:234)
	at test.commons.engine.db.DBQueueItem.execute(DBQueueItem.java:111)
	at org.sqlb.utils.engine.QueueThread.run(QueueThread.java:163)

**Comment by rahrai** [comment]
The error comes while trying get the OLAP connection.
