### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by helkaroui** [pentaho/mondrian#1188]
I'm not able to build the project, Maven doesn't resolve some dependencies

``` 
Cannot resolve plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.17

Cannot resolve plugin org.pentaho:build-helper-maven-plugin:3.1.0

Cannot resolve plugin org.pentaho.maven.plugins:license-helper-maven-plugin:1.27

Cannot resolve plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.17

Cannot resolve plugin org.pentaho:build-helper-maven-plugin:3.1.0

Cannot resolve plugin org.pentaho.maven.plugins:license-helper-maven-plugin:1.27

Cannot resolve plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.17

Cannot resolve plugin org.pentaho:build-helper-maven-plugin:3.1.0

Cannot resolve plugin org.pentaho.maven.plugins:license-helper-maven-plugin:1.27

Cannot resolve plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.17

Cannot resolve plugin org.pentaho:build-helper-maven-plugin:3.1.0

Cannot resolve plugin org.pentaho.maven.plugins:license-helper-maven-plugin:1.27

Cannot resolve plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.17

Cannot resolve plugin org.pentaho:build-helper-maven-plugin:3.1.0

Cannot resolve plugin org.pentaho.maven.plugins:license-helper-maven-plugin:1.27

```

Any help ?

**Comment by AdelB** [comment]
Hi, after a few searches I found the solution : 
They give the solution here : https://github.com/pentaho/pentaho-mondrianschemaworkbench-plugins

1. Download https://github.com/pentaho/maven-parent-poms/blob/master/maven-support-files/settings.xml
2. Put it inside ${user.home}/.m2 directory (C:\users\[yourname]\.m2)
3. Execute the mvn install

**Comment by patdong** [comment]
I followed by the steps and execute the mvn install:
org.apache.maven.InternalErrorException: Internal error: com.google.inject.ProvisionException: Guice provision errors:

1) Could not find a suitable constructor in kr.motd.maven.os.DetectExtension. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at kr.motd.maven.os.DetectExtension.class(Unknown Source)
  while locating kr.motd.maven.os.DetectExtension
  at ClassRealm[extension>kr.motd.maven:os-maven-plugin:1.6.2, parent: sun.misc.Launcher$AppClassLoader@33909752]
  at ClassRealm[extension>kr.motd.maven:os-maven-plugin:1.6.2, parent: sun.misc.Launcher$AppClassLoader@33909752]
  while locating org.apache.maven.AbstractMavenLifecycleParticipant annotated with @com.google.inject.name.Named(value=detect-os)

1 error
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:168)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: com.google.inject.ProvisionException: Guice provision errors:

1) Could not find a suitable constructor in kr.motd.maven.os.DetectExtension. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at kr.motd.maven.os.DetectExtension.class(Unknown Source)
  while locating kr.motd.maven.os.DetectExtension
  at ClassRealm[extension>kr.motd.maven:os-maven-plugin:1.6.2, parent: sun.misc.Launcher$AppClassLoader@33909752]
  at ClassRealm[extension>kr.motd.maven:os-maven-plugin:1.6.2, parent: sun.misc.Launcher$AppClassLoader@33909752]
  while locating org.apache.maven.AbstractMavenLifecycleParticipant annotated with @com.google.inject.name.Named(value=detect-os)

1 error
        at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:974)
        at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
        at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
        at org.sonatype.guice.bean.locators.EntryListAdapter$ValueIterator.next(EntryListAdapter.java:112)
        at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
        at org.apache.maven.DefaultMaven.getLifecycleParticipants(DefaultMaven.java:538)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:270)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        ... 11 more
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException

**Comment by helkaroui** [comment]
The solution given by @AdelB workied fine for me
