### ISSUE TITLE
The Mondrian XML: Mondrian Error:Internal error: query already contains alias

### ISSUE THREAD

**Issue by sanjayraja** [pentaho/mondrian#417]
I Have the following schema xml
```
<Schema name='purchase' metamodelVersion='4.0'>
    <PhysicalSchema>
        <Table name="purchase">
		 <Key>
            <Column name='PurchaseVoucherNumber'/>
         </Key>
        </Table>
        <Table name='dim_date'>
            <Key>
                <Column name='date_key'/>
            </Key>
        </Table>
    </PhysicalSchema>
<Cube name='purchasesCube'>
<Dimensions>
	<Dimension name='Purchase Item' table='purchase' key='Purchase Item Code'>
	<Attributes>
		<Attribute name='Purchase Item Type'  keyColumn='PurchaseItemType' />
		<Attribute name='Purchase Item Group' keyColumn='PurchaseItemGroup' />
		<Attribute name='Purchase Item Category' keyColumn='PurchaseItemCategory' />
		<Attribute name='Purchase Item Code' keyColumn='PurchaseItemCode' />
	</Attributes>
	</Dimension>
</Dimensions>
<MeasureGroups>
<MeasureGroup name='Purchases' table='purchase'>
<Measures>
<Measure name='Number of Deliveries' column='PurchaseVoucherNumber' aggregator='distinct-count' visible='true'>
</Measure>
</Measures>
<DimensionLinks>
<ForeignKeyLink dimension='Purchase Item' foreignKeyColumn='PurchaseItemCode'/>
</DimensionLinks>
</MeasureGroup>
</MeasureGroups>
</Cube>
</Schema>
```
When I execute the following query against this
```
SELECT {[Measures].[Number of Deliveries]} ON columns, {[Purchase Item].[Purchase Item Code].Children} ON rows FROM purchasesCube
```
I get the following error
```
The Mondrian XML: Mondrian Error:Internal error: query already contains alias 'purchase'
```
The resulting SQL query 
```
select
    "purchase"."PurchaseItemCode" as "c0"
from
    "purchase" as "purchase"
group by
    "purchase"."PurchaseItemCode"
order by
    CASE WHEN "purchase"."PurchaseItemCode" IS NULL THEN 0 ELSE 1 END, "purchase"."PurchaseItemCode" ASC
```
Can someone please help point out where I have gone wrong ?
PS: The foodmart examples work just fine.

**Comment by rzorzorzo** [comment]
hello,

any news on this issue ?
i am getting exactly the same error with the following schema:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schema SYSTEM "mondrian.dtd" >
<Schema name="FormsSchema" metamodelVersion="4.0">
<!-- Define how the DB tables are set up -->
<PhysicalSchema>
      <Table name="FORMDATA" schema="REPORTS">
          <Key>
              <Column name="FORM_ID"/>
          </Key>
      </Table>
</PhysicalSchema>
<!-- Create your cube definition and reference back to the physical schema -->
<Cube name="Forms" visible="true" cache="true" enabled="true">
<!-- Define dimensions and attributes -->

<Dimensions>

<Dimension name="Templates" table="FORMDATA" schema="REPORTS" key="TemplateTypes">
              <Attributes>
                  <Attribute name="TemplateTypes" keyColumn="TEMPLATE_ID" hasHierarchy="false"/>
              </Attributes>

              <Hierarchies>
<Hierarchy name="Templates" hasAll="false">
<Level attribute="TemplateTypes"/>
</Hierarchy>
</Hierarchies>

          </Dimension>

</Dimensions>

<!-- Define Measures -->
<MeasureGroups>
          <MeasureGroup name="Forms" table="FORMDATA">
              <Measures>
                  <Measure name="Form Count" column="FORM_ID" aggregator="distinct-count" formatString="Standard"/>
              </Measures>
              <DimensionLinks>
                 <ForeignKeyLink dimension="Templates" foreignKeyColumn="TEMPLATE_ID"/>
              </DimensionLinks>
          </MeasureGroup>
</MeasureGroups>
<!-- Define Calculated Members and Names Sets -->
<CalculatedMembers/>
<NamedSets/>
</Cube>
<!-- If you have conformed dimensions, specify them globally.-->
<!-- Define roles below to restrict access to the cube(s). -->
</Schema>
```

**Comment by mkambol** [comment]
Is the complete stracktrace logged when the error happens?

**Comment by rzorzorzo** [comment]
Hello,

here the stacktrace:

```java
16:45:16,478 ERROR [Query2Resource] Cannot execute query (org.saiku.olap.query2.
ThinQuery@eb9eaf)
org.saiku.service.util.exception.SaikuServiceException: Can't execute query: 6AB
E4CD4-726C-5C35-B167-FA3403153288
        at org.saiku.service.olap.ThinQueryService.execute(ThinQueryService.java
:229)
        at org.saiku.service.olap.ThinQueryService.execute(ThinQueryService.java
:191)
        at org.saiku.service.olap.ThinQueryService.execute(ThinQueryService.java
:183)
        at org.saiku.web.rest.resources.Query2Resource.execute(Query2Resource.ja
va:194)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMe
thodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMeth
odDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvid
er.java:185)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDi
spatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethod
Rule.java:302)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHa
ndPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(Resourc
eClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHa
ndPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(R
ootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequ
est(WebApplicationImpl.java:1542)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequ
est(WebApplicationImpl.java:1473)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleReque
st(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleReque
st(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponen
t.java:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(Servlet
Container.java:558)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(Servlet
Container.java:733)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:206)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.access.intercept.FilterSecurityInter
ceptor.invoke(FilterSecurityInterceptor.java:118)
        at org.springframework.security.web.access.intercept.FilterSecurityInter
ceptor.doFilter(FilterSecurityInterceptor.java:84)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.access.ExceptionTranslationFilter.do
Filter(ExceptionTranslationFilter.java:113)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.session.SessionManagementFilter.doFi
lter(SessionManagementFilter.java:103)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.AnonymousAuthenticati
onFilter.doFilter(AnonymousAuthenticationFilter.java:113)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwar
eRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter
.doFilter(RequestCacheAwareFilter.java:45)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.www.BasicAuthenticati
onFilter.doFilter(BasicAuthenticationFilter.java:150)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.ui.DefaultLoginPageGe
neratingFilter.doFilter(DefaultLoginPageGeneratingFilter.java:155)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.AbstractAuthenticatio
nProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.logout.LogoutFilter.d
oFilter(LogoutFilter.java:110)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.context.SecurityContextPersistenceFi
lter.doFilter(SecurityContextPersistenceFilter.java:87)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(Fi
lterChainProxy.java:192)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChai
nProxy.java:160)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(D
elegatingFilterProxy.java:346)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(Delegat
ingFilterProxy.java:259)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperV
alve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextV
alve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j
ava:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j
ava:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineVal
ve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav
a:298)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java
:852)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.proce
ss(Http11Protocol.java:588)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:48
9)
        at java.lang.Thread.run(Thread.java:744)
Caused by: org.olap4j.OlapException: mondrian gave exception while executing que
ry
        at mondrian.olap4j.MondrianOlap4jConnection$Helper.createException(Mondr
ianOlap4jConnection.java:842)
        at mondrian.olap4j.MondrianOlap4jStatement.executeOlapQueryInternal(Mond
rianOlap4jStatement.java:421)
        at mondrian.olap4j.MondrianOlap4jStatement.executeOlapQuery(MondrianOlap
4jStatement.java:347)
        at org.saiku.service.olap.ThinQueryService.executeInternalQuery(ThinQuer
yService.java:169)
        at org.saiku.service.olap.ThinQueryService.execute(ThinQueryService.java
:212)
        ... 65 more
Caused by: mondrian.olap.MondrianException: Mondrian Error:Internal error: Error
 while executing query [with set [~ROWS] as '{[Templates].[Templates].[TemplateT
ypes].Members}'
select NON EMPTY {[Measures].[Form Count]} ON COLUMNS,
  NON EMPTY [~ROWS] ON ROWS
from [Forms]
]
        at mondrian.resource.MondrianResource$_Def0.ex(MondrianResource.java:987
)
        at mondrian.olap.Util.newInternal(Util.java:2543)
        at mondrian.olap.Util.newError(Util.java:2559)
        at mondrian.rolap.RolapConnection.executeInternal(RolapConnection.java:5
35)
        at mondrian.rolap.RolapConnection.access$000(RolapConnection.java:45)
        at mondrian.rolap.RolapConnection$1.call(RolapConnection.java:448)
        at mondrian.rolap.RolapConnection$1.call(RolapConnection.java:446)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:615)
        ... 1 more
Caused by: mondrian.olap.MondrianException: Mondrian Error:mondrian.olap.Mondria
nException: Mondrian Error:Internal error: query already contains alias 'FORMDAT
A'
        at mondrian.rolap.agg.SegmentLoader.loadImpl(SegmentLoader.java:241)
        at mondrian.rolap.agg.SegmentLoader$SegmentLoadCommand.call(SegmentLoade
r.java:166)
        at mondrian.rolap.agg.SegmentLoader$SegmentLoadCommand.call(SegmentLoade
r.java:140)
        ... 4 more
Caused by: mondrian.olap.MondrianException: Mondrian Error:Internal error: query
 already contains alias 'FORMDATA'
        at mondrian.resource.MondrianResource$_Def0.ex(MondrianResource.java:984
)
        at mondrian.olap.Util.newInternal(Util.java:2536)
        at mondrian.rolap.sql.SqlQuery.addFromTable(SqlQuery.java:264)
        at mondrian.rolap.sql.SqlQuery.addFrom_(SqlQuery.java:377)
        at mondrian.rolap.sql.SqlQuery.addFrom(SqlQuery.java:346)
        at mondrian.rolap.sql.SqlQueryBuilder$ProtectedSqlQuery.addFromSuper(Sql
QueryBuilder.java:593)
        at mondrian.rolap.sql.SqlQueryBuilder.addRecursive(SqlQueryBuilder.java:
365)
        at mondrian.rolap.sql.SqlQueryBuilder.flush(SqlQueryBuilder.java:347)
        at mondrian.rolap.sql.SqlQueryBuilder.toSqlAndTypes(SqlQueryBuilder.java
:377)
        at mondrian.rolap.agg.AbstractQuerySpec.generateSqlQuery(AbstractQuerySp
ec.java:191)
        at mondrian.rolap.agg.AggregationManager.generateSql(AggregationManager.
java:323)
        at mondrian.rolap.agg.SegmentLoader.createExecuteSql(SegmentLoader.java:
569)
        at mondrian.rolap.agg.SegmentLoader.loadImpl(SegmentLoader.java:195)
        ... 6 more

```

**Comment by mkambol** [comment]
Your [Templates] dimension is degenerate-- it's directly on the fact table.  Because of that you should use a <FactLink> instead of <ForeignKeyLink>, otherwise Mondrian will attempt to join to a separate dim table and fail when the alias is already present.

Try: 
 <FactLink  dimension="Templates" />

**Comment by rzorzorzo** [comment]
hello,

yes, that solved it. Thanks !

**Comment by mjbrydon** [comment]
magic

**Comment by mkambol** [comment]
BTW- created http://jira.pentaho.com/browse/MONDRIAN-2354 to give a more informative error, or potentially just allow degenerates to be defined with ForeignKeyLinks.

**Comment by deynesonborba** [comment]
Great tip, thanks!
