### ISSUE TITLE
NullPointer Exception After Adding Closure Table On Xml Schema

### ISSUE THREAD

**Issue by castalheiro** [pentaho/mondrian#454]
The XML definitions:

   </PhysicalSchema>
        <Table name='space_dimension'>
            <Key>
                <Column name='space_id'/>
            </Key>
            <ColumnDefs>
                <ColumnDef name='space_id' type='Integer'/>
                <ColumnDef name='parent_space_id' type='Integer'/>
                <ColumnDef name='space_name' type='String'/>
                <ColumnDef name='space_type' type='String'/>
                <ColumnDef name='space_description' type='String'/>
                <ColumnDef name='space_area' type='Integer'/>
                <ColumnDef name='has_natural_light' type='Boolean'/>
            </ColumnDefs>
        </Table>
        <Table name='space_hierarchy_bridge'>
            <Key>
                <Column name='space_id'/>
            </Key>
            <ColumnDefs>
                <ColumnDef name='space_id' type='Integer'/>
                <ColumnDef name='parent_space_id' type='Integer'/>
                <ColumnDef name='levels_from_top' type='Integer'/>
                <ColumnDef name='bottom_flag' type='Boolean'/>
                <ColumnDef name='top_flag' type='Boolean'/>
            </ColumnDefs>
        </Table>
       <Link source='space_dimension' target='space_hierarchy_bridge'>
            <ForeignKey>
                <Column name='space_id'/>
            </ForeignKey>
        </Link>
    </PhysicalSchema>

      <Dimension name='Space' table='space_dimension' key='Space Id'>
        <Attributes>
            <Attribute name='Parent Space Id' keyColumn='parent_space_id' approxRowCount='4772'/>
            <Attribute name='Space Id' keyColumn='space_id' approxRowCount='4772'/>
            <Attribute name='Space Name' keyColumn='space_name' approxRowCount='2013'/>
            <Attribute name='Space Type' keyColumn='space_type' approxRowCount='5'/>
            <Attribute name='Space Description' keyColumn='space_description' approxRowCount='833'/>
            <Attribute name='Space Area' keyColumn='space_area' approxRowCount='1159'/>
            <Attribute name='Has Natural Light' keyColumn='has_natural_light' approxRowCount='2'/>
        </Attributes>
        <Hierarchies>
            <Hierarchy name='Space' primaryKey="space_id">
                <Level attribute='Parent Space Id'/>
                <Level attribute='Space Name' parentAttribute='Parent Space Id' nullParentValue='0'>
                    <Closure table='space_hierarchy_bridge' parentColumn='parent_space_id' childColumn='space_id'/>
                </Level>
            </Hierarchy>
        </Hierarchies>
    </Dimension>

The SQL Definitions:

CREATE TABLE space_dimension(
parent_space_id BIGINT NOT NULL,
space_id BIGINT NOT NULL,
space_name VARCHAR NOT NULL,
space_type VARCHAR NOT NULL,
space_description VARCHAR NOT NULL DEFAULT 'No Description',
space_area BIGINT NOT NULL DEFAULT 0,
has_natural_light BOOLEAN NOT NULL DEFAULT FALSE,
CONSTRAINT pk_space_dimension PRIMARY KEY (space_id)
);

CREATE TABLE space_hierarchy_bridge(
parent_space_id BIGINT NOT NULL,
space_id BIGINT NOT NULL,
levels_from_top INT NOT NULL,
bottom_flag BOOLEAN NOT NULL,
top_flag BOOLEAN NOT NULL,
FOREIGN KEY (space_id) REFERENCES space_dimension (space_id)
);

The error that shows up has soon as i load the mondrian library:

java.lang.NullPointerException
        at mondrian.rolap.RolapSchema$PhysPathBuilder.<init>(RolapSchema.java:2554)
        at mondrian.rolap.RolapSchemaLoader.registerExpr(RolapSchemaLoader.java:2219)
        at mondrian.rolap.RolapSchemaLoader.registerAttribute(RolapSchemaLoader.java:2165)
        at mondrian.rolap.RolapSchemaLoader.registerLevel(RolapSchemaLoader.java:2150)
        at mondrian.rolap.RolapSchemaLoader.registerHierarchy(RolapSchemaLoader.java:2139)
        at mondrian.rolap.RolapSchemaLoader.registerDimension(RolapSchemaLoader.java:2127)
        at mondrian.rolap.RolapSchemaLoader.createCube(RolapSchemaLoader.java:1907)
        at mondrian.rolap.RolapSchemaLoader.sharedDimension(RolapSchemaLoader.java:3062)
        at mondrian.rolap.RolapSchemaLoader.access$500(RolapSchemaLoader.java:62)
        at mondrian.rolap.RolapSchemaLoader$5.apply(RolapSchemaLoader.java:2731)
        at mondrian.rolap.RolapSchemaLoader.loadStage2(RolapSchemaLoader.java:426)
        at mondrian.rolap.RolapSchemaLoader.loadStage1(RolapSchemaLoader.java:336)
        at mondrian.rolap.RolapSchemaLoader.loadStage0(RolapSchemaLoader.java:272)
        at mondrian.rolap.RolapSchemaLoader.createSchema(RolapSchemaLoader.java:4303)
        at mondrian.rolap.RolapSchemaPool.get(RolapSchemaPool.java:210)
        at mondrian.rolap.RolapSchemaPool.get(RolapSchemaPool.java:62)
        at mondrian.rolap.RolapConnection.<init>(RolapConnection.java:160)
        at mondrian.rolap.RolapConnection.<init>(RolapConnection.java:84)
        at mondrian.olap.DriverManager.getConnection(DriverManager.java:112)
        at mondrian.olap.DriverManager.getConnection(DriverManager.java:68)
        at mondrian.olap4j.MondrianOlap4jConnection.<init>(MondrianOlap4jConnection.java:153)
        at mondrian.olap4j.FactoryJdbc4Plus$AbstractConnection.<init>(FactoryJdbc4Plus.java:323)
        at mondrian.olap4j.FactoryJdbc41Impl$MondrianOlap4jConnectionJdbc41.<init>(FactoryJdbc41Impl.java:118)
        at mondrian.olap4j.FactoryJdbc41Impl.newConnection(FactoryJdbc41Impl.java:32)
        at mondrian.olap4j.MondrianOlap4jDriver.connect(MondrianOlap4jDriver.java:139)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at energydw.olap.application.Application.init(Application.java:148)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:612)
        at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:468)
        at org.eclipse.jetty.servlet.ServletHolder.ensureInstance(ServletHolder.java:763)
        at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:748)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Unknown Source)
2015-04-09 13:02:56.567:WARN:oejs.ServletHandler:qtp1031980531-17:
javax.servlet.ServletException: energydw.olap.application.Application@92789c63==energydw.olap.application.Application,-1,fa
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:633)
        at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:468)
        at org.eclipse.jetty.servlet.ServletHolder.ensureInstance(ServletHolder.java:763)
        at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:748)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Unknown Source)
Caused by:
java.lang.NullPointerException
        at mondrian.rolap.RolapSchema$PhysPathBuilder.<init>(RolapSchema.java:2554)
        at mondrian.rolap.RolapSchemaLoader.registerExpr(RolapSchemaLoader.java:2219)
        at mondrian.rolap.RolapSchemaLoader.registerAttribute(RolapSchemaLoader.java:2165)
        at mondrian.rolap.RolapSchemaLoader.registerLevel(RolapSchemaLoader.java:2150)
        at mondrian.rolap.RolapSchemaLoader.registerHierarchy(RolapSchemaLoader.java:2139)
        at mondrian.rolap.RolapSchemaLoader.registerDimension(RolapSchemaLoader.java:2127)
        at mondrian.rolap.RolapSchemaLoader.createCube(RolapSchemaLoader.java:1907)
        at mondrian.rolap.RolapSchemaLoader.sharedDimension(RolapSchemaLoader.java:3062)
        at mondrian.rolap.RolapSchemaLoader.access$500(RolapSchemaLoader.java:62)
        at mondrian.rolap.RolapSchemaLoader$5.apply(RolapSchemaLoader.java:2731)
        at mondrian.rolap.RolapSchemaLoader.loadStage2(RolapSchemaLoader.java:426)
        at mondrian.rolap.RolapSchemaLoader.loadStage1(RolapSchemaLoader.java:336)
        at mondrian.rolap.RolapSchemaLoader.loadStage0(RolapSchemaLoader.java:272)
        at mondrian.rolap.RolapSchemaLoader.createSchema(RolapSchemaLoader.java:4303)
        at mondrian.rolap.RolapSchemaPool.get(RolapSchemaPool.java:210)
        at mondrian.rolap.RolapSchemaPool.get(RolapSchemaPool.java:62)
        at mondrian.rolap.RolapConnection.<init>(RolapConnection.java:160)
        at mondrian.rolap.RolapConnection.<init>(RolapConnection.java:84)
        at mondrian.olap.DriverManager.getConnection(DriverManager.java:112)
        at mondrian.olap.DriverManager.getConnection(DriverManager.java:68)
        at mondrian.olap4j.MondrianOlap4jConnection.<init>(MondrianOlap4jConnection.java:153)
        at mondrian.olap4j.FactoryJdbc4Plus$AbstractConnection.<init>(FactoryJdbc4Plus.java:323)
        at mondrian.olap4j.FactoryJdbc41Impl$MondrianOlap4jConnectionJdbc41.<init>(FactoryJdbc41Impl.java:118)
        at mondrian.olap4j.FactoryJdbc41Impl.newConnection(FactoryJdbc41Impl.java:32)
        at mondrian.olap4j.MondrianOlap4jDriver.connect(MondrianOlap4jDriver.java:139)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at energydw.olap.application.Application.init(Application.java:148)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:612)
        at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:468)
        at org.eclipse.jetty.servlet.ServletHolder.ensureInstance(ServletHolder.java:763)
        at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:748)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Unknown Source)

Everything was working fine before i added the closure definition

**Comment by konrad-garus** [comment]
This is still an issue in 4.3.0.1-130.
